import { AuditLogEvent, Guild, PermissionFlagsBits, TextChannel } from 'discord.js';
import db from '../db';
import { getGuildSettings } from '../db/settings';
import { enableLockdown } from '../security/lockdown';
import { info, warn } from '../logger';

type Action = 'CHANNEL_DELETE'|'ROLE_DELETE'|'BAN'|'KICK'|'CHANNEL_UPDATE'|'ROLE_UPDATE';
const recent=new Map<string,Array<{executor:string;ts:number;action:Action}>>();
const triggered=new Map<string,number>();
const auditType:Record<Action,AuditLogEvent>={CHANNEL_DELETE:AuditLogEvent.ChannelDelete,ROLE_DELETE:AuditLogEvent.RoleDelete,BAN:AuditLogEvent.MemberBanAdd,KICK:AuditLogEvent.MemberKick,CHANNEL_UPDATE:AuditLogEvent.ChannelUpdate,ROLE_UPDATE:AuditLogEvent.RoleUpdate};
const DANGEROUS=BigInt(PermissionFlagsBits.Administrator)|BigInt(PermissionFlagsBits.ManageGuild)|BigInt(PermissionFlagsBits.ManageChannels)|BigInt(PermissionFlagsBits.ManageRoles)|BigInt(PermissionFlagsBits.BanMembers)|BigInt(PermissionFlagsBits.KickMembers)|BigInt(PermissionFlagsBits.ModerateMembers);
function trusted(settings:any,id:string,guild:Guild){return id===guild.ownerId||id===guild.client.user?.id||(settings.security_trusted_users||'').split(',').map((x:string)=>x.trim()).filter(Boolean).includes(id)}
async function alert(guild:Guild,action:string,executor:string,count:number){const id=getGuildSettings(guild.id).mod_log_channel;if(!id)return;const channel=guild.channels.cache.get(id);if(channel instanceof TextChannel)await channel.send(`🚨 **Security Alert**\nAction: \`${action}\`\nExecutor: <@${executor}> (${executor})\nDetected actions: **${count}**`).catch(()=>{});}
function roleEscalation(oldRole:any,newRole:any){const oldBits=BigInt(oldRole.permissions.bitfield),newBits=BigInt(newRole.permissions.bitfield);return (newBits&~oldBits&DANGEROUS)!==0n;}
function channelEscalation(oldChannel:any,newChannel:any){const ids=new Set<string>([...oldChannel.permissionOverwrites.cache.keys(),...newChannel.permissionOverwrites.cache.keys()]);for(const id of ids){const a=oldChannel.permissionOverwrites.cache.get(id),b=newChannel.permissionOverwrites.cache.get(id);const oldAllow=BigInt(a?.allow?.bitfield??0),newAllow=BigInt(b?.allow?.bitfield??0),oldDeny=BigInt(a?.deny?.bitfield??0),newDeny=BigInt(b?.deny?.bitfield??0);if((newAllow&~oldAllow&DANGEROUS)!==0n||(oldDeny&~newDeny&DANGEROUS)!==0n)return true;}return false;}
export function isRolePermissionEscalation(oldRole:any,newRole:any){return roleEscalation(oldRole,newRole)}
export function isChannelPermissionEscalation(oldChannel:any,newChannel:any){return channelEscalation(oldChannel,newChannel)}
export async function confirmKick(guild:Guild,userId:string){try{const logs=await guild.fetchAuditLogs({limit:10,type:AuditLogEvent.MemberKick}),now=Date.now();return logs.entries.find(x=>x.target?.id===userId&&now-x.createdTimestamp<10000)?.executor?.id??null;}catch{return null;}}
export async function recordDestructiveAction(guild:Guild,action:Action,targetId?:string,knownExecutorId?:string){try{const settings=getGuildSettings(guild.id);if(!settings.security_enabled)return;const now=Date.now(),executorId=knownExecutorId??await findExecutor(guild,action,targetId,now);if(!executorId||trusted(settings,executorId,guild))return;const window=Math.max(10,Math.min(600,settings.security_window_seconds))*1000;const arr=(recent.get(guild.id)||[]).filter(x=>now-x.ts<=window);arr.push({executor:executorId,ts:now,action});recent.set(guild.id,arr);db.prepare('INSERT INTO audit_events(guild_id,action,target_id,executor_id,timestamp) VALUES(?,?,?,?,?)').run(guild.id,action,targetId??null,executorId,now);const count=arr.filter(x=>x.executor===executorId).length;await alert(guild,action,executorId,count);const threshold=Math.max(2,Math.min(50,settings.security_threshold));if(count<threshold)return;const triggerKey=`${guild.id}:${executorId}`,last=triggered.get(triggerKey)??0;if(now-last<window)return;triggered.set(triggerKey,now);const mode=settings.security_action;if(mode==='lockdown'||mode==='ban_and_lockdown'){const result=await enableLockdown(guild,`Anti-nuke threshold reached by ${executorId}`);if(!result.ok)warn('Anti-nuke lockdown could not be applied',result.reason);}const member=guild.members.cache.get(executorId)||await guild.members.fetch(executorId).catch(()=>null),bot=guild.members.me;if(mode==='ban_and_lockdown'&&member&&bot&&executorId!==guild.ownerId&&member.id!==bot.id&&member.roles.highest.position<bot.roles.highest.position&&bot.permissions.has(PermissionFlagsBits.BanMembers))await member.ban({reason:'Anti-nuke: repeated destructive actions'}).then(()=>info('Anti-nuke blocked executor',executorId)).catch(e=>warn('Anti-nuke ban failed',e));}catch(e){warn('recordDestructiveAction error',e instanceof Error?e.message:String(e));}}
async function findExecutor(guild:Guild,action:Action,targetId:string|undefined,now:number){try{const logs=await guild.fetchAuditLogs({limit:10,type:auditType[action]});return logs.entries.find(x=>(!targetId||x.target?.id===targetId)&&now-x.createdTimestamp<10000)?.executor?.id??null;}catch{return null;}}
setInterval(()=>{const cutoff=Date.now()-15*60_000;for(const[k,v]of recent)if(!v.length||v[v.length-1].ts<cutoff)recent.delete(k);for(const[k,v]of triggered)if(v<cutoff)triggered.delete(k)},60_000).unref();
