const cocOriginalRender=render;
let cocData=null;
function cocEscape(v){return esc(v);}
function cocNum(v){return Number(v||0).toLocaleString();}
function cocPct(v){return `${Number(v||0).toFixed(1)}%`;}
async function cocLoad(){try{cocData=await api(`/api/guild/${state.guild}/coc`);cocRender();}catch(e){$('#content').innerHTML=`<div class="card"><h3>⚔️ Clash of Clans</h3><p class="danger">${cocEscape(e.message)}</p></div>`;}}
function cocRender(){const d=cocData||{},c=d.clan;$('#pageTitle').textContent='Clash of Clans';$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view==='coc'));
 if(!d.configured||!d.tag){$('#content').innerHTML=`<div class="two"><div class="card"><p class="eyebrow">COC COMMAND CENTER</p><h3>Connect your clan</h3><p class="muted">Unlock live clan, roster, war, CWL, Capital and recruitment intelligence.</p><div class="form"><div class="field"><label>Clan tag</label><input id="cocTag" maxlength="16" placeholder="#ABC123" value="${cocEscape(d.tag||'')}"></div><button class="btn primary" onclick="cocSave()">Connect clan</button></div></div><div class="card"><h3>API status</h3><div class="list"><div class="row"><span>CoC API</span><b class="${d.configured?'goodtext':'danger'}">${d.configured?'Configured':'Not configured'}</b></div><div class="row"><span>Server clan</span><b>${d.tag||'Not connected'}</b></div></div></div></div>`;return;}
 if(!c){$('#content').innerHTML=`<div class="card"><h3>⚔️ Clash of Clans</h3><p class="danger">Unable to load clan data.</p></div>`;return;}
 const members=d.members||[],th=Object.entries(c.townHalls||{}).sort((a,b)=>Number(b[0])-Number(a[0])).map(([k,v])=>`<span class="pill">TH${cocEscape(k)} · ${v}</span>`).join(' '),w=d.warSummary||null;
 const warText=!w?'Unavailable':w.state==='notInWar'?'Not currently in war':`${cocEscape(w.ourSide?.name||'Clan')} <b>${w.ourSide?.stars||0}</b> — <b>${w.opponent?.stars||0}</b> ${cocEscape(w.opponent?.name||'Opponent')}`;
 const roster=members.slice().sort((a,b)=>Number(b.townHallLevel||0)-Number(a.townHallLevel||0)||Number(b.trophies||0)-Number(a.trophies||0)).slice(0,15).map(m=>`<div class="row"><span><b>${cocEscape(m.name)}</b><br><span class="muted">TH${cocEscape(m.townHallLevel)} · ${cocNum(m.trophies)} 🏆 · Rank #${cocNum(m.clanRank)}</span></span><span>${cocNum(m.donations)} donated</span></div>`).join('');
 const log=(d.warlog||[]).slice(0,6).map(x=>`<div class="row"><span>${x.result==='win'?'🟢':x.result==='lose'?'🔴':'⚪'} ${cocEscape(x.opponent?.name||'Opponent')}</span><b>${x.clan?.stars??0}-${x.opponent?.stars??0}</b></div>`).join('')||'<span class="muted">No recent wars.</span>';
 const cwl=(d.cwl?.clans||[]).map(x=>`<div class="row"><span>${cocEscape(x.name)}</span><span class="muted">${cocEscape(x.tag)}</span></div>`).join('')||'<span class="muted">No active CWL group.</span>';
 const raids=(d.raids||[]).slice(0,5).map(x=>`<div class="row"><span>🏯 ${cocEscape(x.startTime||'Raid Weekend')}</span><span>${cocNum(x.attackCount)} attacks · ${cocNum(x.offensiveReward)} medals</span></div>`).join('')||'<span class="muted">No raid history.</span>';
 $('#content').innerHTML=`<div class="grid"><div class="card metric"><div class="label">MEMBERS</div><div class="value">${cocNum(c.members)}</div><div class="sub">of 50</div></div><div class="card metric"><div class="label">CLAN LEVEL</div><div class="value">${cocNum(c.level)}</div><div class="sub">${cocEscape(c.warLeague)}</div></div><div class="card metric"><div class="label">WAR WINS</div><div class="value">${cocNum(c.warWins)}</div><div class="sub">Streak ${cocNum(c.warWinStreak)}</div></div><div class="card metric"><div class="label">DONATIONS</div><div class="value">${cocNum(c.totalDonations)}</div><div class="sub">${cocNum(c.totalReceived)} received</div></div></div><div class="card section"><div class="actions" style="justify-content:space-between;align-items:center"><div><p class="eyebrow">CONNECTED CLAN</p><h3>🏰 ${cocEscape(c.name)}</h3><span class="muted">${cocEscape(c.tag)}</span></div><div class="actions"><button class="btn" onclick="cocRefresh()">↻ Refresh</button><button class="btn" onclick="cocConfigure()">⚙ Configure</button></div></div><div style="margin-top:14px">${th||'<span class="muted">No Town Hall data.</span>'}</div></div><div class="two section"><div class="card"><h3>⚔️ Live War</h3><div class="list"><div class="row"><span>${warText}</span><span class="muted">${w?.state||'—'}</span></div><div class="row"><span>Destruction</span><b>${cocPct(w?.ourSide?.destructionPercentage)} — ${cocPct(w?.opponent?.destructionPercentage)}</b></div><div class="row"><span>Attacks</span><b>${cocNum(w?.used)} / ${cocNum(w?.possible)}</b></div><div class="row"><span>Remaining</span><b>${cocNum(w?.remaining)}</b></div></div></div><div class="card"><h3>🏆 CWL</h3><div class="list">${cwl}</div></div></div><div class="two section"><div class="card"><h3>👥 Roster Intelligence</h3><div class="list">${roster||'<span class="muted">No members returned.</span>'}</div></div><div class="card"><h3>📜 War History</h3><div class="list">${log}</div></div></div><div class="card section"><h3>🏯 Clan Capital</h3><div class="list">${raids}</div></div>`;}
async function cocSave(){const tag=$('#cocTag')?.value.trim()||'';try{await api(`/api/guild/${state.guild}/coc/config`,{method:'POST',body:JSON.stringify({tag})});toast('Clan connected');await cocLoad();}catch(e){toast(e.message)}}
async function cocRefresh(){await cocLoad();}
function cocConfigure(){const current=cocData?.tag||'';$('#content').innerHTML=`<div class="card"><p class="eyebrow">CLAN CONFIGURATION</p><h3>Connect a clan</h3><p class="muted">The API token stays server-side. Only the clan tag is stored per Discord server.</p><div class="form"><div class="field"><label>Clan tag</label><input id="cocTag" maxlength="16" value="${cocEscape(current)}" placeholder="#ABC123"></div><div class="actions"><button class="btn primary" onclick="cocSave()">Save</button><button class="btn" onclick="cocLoad()">Cancel</button></div></div></div>`;}
function cocPage(){cocLoad();}
render=function(){if(state.view==='coc')cocPage();else cocOriginalRender();};
