import { ActivityType, PresenceStatusData, SlashCommandBuilder } from 'discord.js';
import db from '../db';
import { getGuildSettings, setGuildSetting } from '../db/settings';
import { applyStatusSettings } from '../services/status';
const types:any={playing:ActivityType.Playing,watching:ActivityType.Watching,listening:ActivityType.Listening,streaming:ActivityType.Streaming,competing:ActivityType.Competing};
const data=new SlashCommandBuilder().setName('status').setDescription('Configure bot presence').addStringOption(o=>o.setName('action').setDescription('Action').setRequired(true).addChoices({name:'add',value:'add'},{name:'remove-all',value:'remove-all'},{name:'rotation-on',value:'rotation-on'},{name:'rotation-off',value:'rotation-off'},{name:'view',value:'view'},{name:'set',value:'set'})).addStringOption(o=>o.setName('text').setDescription('Status text')).addStringOption(o=>o.setName('type').setDescription('Activity').addChoices({name:'playing',value:'playing'},{name:'watching',value:'watching'},{name:'listening',value:'listening'},{name:'streaming',value:'streaming'},{name:'competing',value:'competing'})).addStringOption(o=>o.setName('presence').setDescription('Online state').addChoices({name:'online',value:'online'},{name:'idle',value:'idle'},{name:'dnd',value:'dnd'},{name:'invisible',value:'invisible'})).addIntegerOption(o=>o.setName('interval').setDescription('Rotation seconds').setMinValue(15).setMaxValue(3600));
function ensure(i:any){if(i.user?.id!==(process.env.OWNER_ID||''))throw new Error('Owner only.');if(!i.guild)throw new Error('Guild only.');}
async function run(i:any,a:string,t:string|null,type:string,presence:string|null,interval:number|null){ensure(i);const g=i.guild.id;if(a==='add'){if(!t||t.length>128)throw new Error('Status text is required and must be <=128 characters.');const p=(db.prepare('SELECT COALESCE(MAX(position),-1)+1 p FROM statuses WHERE guild_id=?').get(g) as any).p;db.prepare('INSERT INTO statuses(guild_id,text,type,position) VALUES(?,?,?,?)').run(g,t,type.toUpperCase(),p);}
else if(a==='remove-all')db.prepare('DELETE FROM statuses WHERE guild_id=?').run(g);
else if(a==='rotation-on'){setGuildSetting(g,'status_rotation_enabled',1);if(interval)setGuildSetting(g,'status_rotation_interval',interval);await applyStatusSettings(i.client);}
else if(a==='rotation-off'){setGuildSetting(g,'status_rotation_enabled',0);}
else if(a==='set'){if(!t||t.length>128)throw new Error('Status text is required and must be <=128 characters.');i.client.user?.setPresence({status:(presence||'online') as PresenceStatusData,activities:[{name:t,type:types[type]??ActivityType.Playing}]});}
else {const rows:any[]=db.prepare('SELECT text,type FROM statuses WHERE guild_id=? ORDER BY position,id').all(g);return rows.length?rows.map(x=>`${x.type}: ${x.text}`).join('\n'):'No statuses configured.';}
if(a!=='view'&&a!=='set')await applyStatusSettings(i.client);return a==='remove-all'?'All statuses removed.':a==='add'?'Status added.':a==='rotation-on'?'Status rotation enabled.':a==='rotation-off'?'Status rotation disabled.':'Presence updated.';}
async function executeSlash(i:any){try{return i.reply({content:await run(i,i.options.getString('action',true),i.options.getString('text'),i.options.getString('type')||'playing',i.options.getString('presence'),i.options.getInteger('interval')),ephemeral:true});}catch(e){return i.reply({content:e instanceof Error?e.message:'Invalid status request.',ephemeral:true});}}
async function executePrefix(m:any,args:string[]){const fake={...m,user:m.author,options:{getString:(n:string)=>n==='action'?args[0]:n==='text'?args.slice(1).join(' '):n==='type'?'playing':'online',getInteger:()=>null}};try{return m.reply(await run(fake,args[0]||'view',args.slice(1).join(' ')||null,'playing','online',null));}catch(e){return m.reply(e instanceof Error?e.message:'Invalid status request.');}}
export={name:'status',description:'Configure bot presence',ownerOnly:true,cooldown:2,data,executeSlash,executePrefix};
