import { SlashCommandBuilder } from 'discord.js';
import db from '../db';
import { getGuildSettings, setGuildSetting } from '../db/settings';
import { applyStatusSettings } from '../services/status';
const data=new SlashCommandBuilder().setName('status').setDescription('Configure bot status').addStringOption(o=>o.setName('action').setDescription('Action').setRequired(true).addChoices({name:'add',value:'add'},{name:'remove-all',value:'remove-all'},{name:'rotation-on',value:'rotation-on'},{name:'rotation-off',value:'rotation-off'},{name:'view',value:'view'})).addStringOption(o=>o.setName('text').setDescription('Status text')).addStringOption(o=>o.setName('type').setDescription('Activity type').addChoices({name:'playing',value:'PLAYING'},{name:'watching',value:'WATCHING'},{name:'listening',value:'LISTENING'},{name:'competing',value:'COMPETING'})).addIntegerOption(o=>o.setName('interval').setDescription('Rotation seconds').setMinValue(15).setMaxValue(3600));
function run(i:any){if(i.user.id!==(process.env.OWNER_ID||''))throw new Error('Owner only.');const g=i.guild.id,a=i.options.getString('action',true),t=i.options.getString('text'),type=i.options.getString('type')||'PLAYING';if(a==='add'){if(!t||t.length>128)throw new Error('Status text is required and must be <=128 characters.');const pos=(db.prepare('SELECT COALESCE(MAX(position),-1)+1 p FROM statuses WHERE guild_id=?').get(g) as any).p;db.prepare('INSERT INTO statuses(guild_id,text,type,position) VALUES(?,?,?,?)').run(g,t,type,pos);return 'Status added.';}if(a==='remove-all'){db.prepare('DELETE FROM statuses WHERE guild_id=?').run(g);return 'All statuses removed.';}if(a==='rotation-on'){setGuildSetting(g,'status_rotation_enabled',1);const interval=i.options.getInteger('interval');if(interval)setGuildSetting(g,'status_rotation_interval',interval);void applyStatusSettings(i.client);return 'Status rotation enabled.';}if(a==='rotation-off'){setGuildSetting(g,'status_rotation_enabled',0);return 'Status rotation disabled.';}const rows=db.prepare('SELECT text,type FROM statuses WHERE guild_id=? ORDER BY position').all(g) as Array<{text:string,type:string}>;return rows.length?rows.map(x=>`${x.type}: ${x.text}`).join('\n'):'No statuses configured.';}
async function executeSlash(i:any){try{return i.reply({content:run(i),ephemeral:true});}catch(e){return i.reply({content:e instanceof Error?e.message:'Invalid request.',ephemeral:true});}}
async function executePrefix(m:any){return m.reply('Use /status for status management.');}
export={name:'status',description:'Configure bot status',ownerOnly:true,data,executeSlash,executePrefix};
