import crypto from 'crypto';
import express, { type Request, type Response } from 'express';
import path from 'path';
import type { Client } from 'discord.js';
import { PermissionFlagsBits } from 'discord.js';
import db from './db';
import { getGuildSettings, setGuildSetting } from './db/settings';
import { enableLockdown, disableLockdown } from './security/lockdown';

const SESSION_COOKIE='dashboard_session';
const OAUTH_STATE_COOKIE='dashboard_oauth_state';
const SESSION_TTL=24*60*60*1000;
const OAUTH_STATE_TTL=10*60*1000;
const secret=process.env.SESSION_SECRET||process.env.DASHBOARD_SESSION_SECRET;
if(!secret)console.warn('[Dashboard] SESSION_SECRET is not set; dashboard login is disabled until it is configured.');
const key=secret?crypto.createHash('sha256').update(secret).digest():null;
const rate=new Map<string,{window:number;count:number}>();
function b64(buf:Buffer){return buf.toString('base64url')}
function unb64(v:string){return Buffer.from(v,'base64url')}
function seal(payload:object){if(!key)throw new Error('Dashboard session secret is not configured.');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.from(JSON.stringify(payload)),encrypted=Buffer.concat([cipher.update(body),cipher.final()]);return `${b64(iv)}.${b64(cipher.getAuthTag())}.${b64(encrypted)}`}
function open(token:string){if(!key)return null;try{const [iv,tag,encrypted]=token.split('.');if(!iv||!tag||!encrypted)return null;const decipher=crypto.createDecipheriv('aes-256-gcm',key,unb64(iv));decipher.setAuthTag(unb64(tag));return JSON.parse(Buffer.concat([decipher.update(unb64(encrypted)),decipher.final()]).toString()) as {userId:string;username:string;accessToken:string;csrf:string;exp:number}}catch{return null}}
function cookie(req:Request,name:string){return req.headers.cookie?.match(new RegExp(`(?:^|;\\s*)${name}=([^;]+)`))?.[1]}
function getSession(req:Request){const token=cookie(req,SESSION_COOKIE);if(!token)return null;const data=open(decodeURIComponent(token));if(!data||data.exp<Date.now())return null;return data}
function origin(req:Request){if(process.env.DASHBOARD_PUBLIC_URL)return process.env.DASHBOARD_PUBLIC_URL.replace(/\/$/,'');const proto=req.headers['x-forwarded-proto']?.toString().split(',')[0]||req.protocol;const host=req.headers['x-forwarded-host']?.toString().split(',')[0]||req.get('host');return `${proto}://${host}`}
function redirectUri(req:Request){return process.env.DISCORD_REDIRECT_URI||`${origin(req)}/auth/callback`}
async function discordJson(url:string,init?:RequestInit){const r=await fetch(url,init);if(!r.ok)throw new Error(`Discord API ${r.status}`);return r.json() as Promise<any>}
function clientIp(req:Request){return req.ip||req.socket.remoteAddress||'unknown'}
function rateLimit(req:Request,res:Response,limit:number,windowMs:number){const key=`${clientIp(req)}:${req.path}`;const now=Date.now();const old=rate.get(key);if(!old||now-old.window>=windowMs){rate.set(key,{window:now,count:1});return true}old.count++;if(old.count>limit){res.setHeader('Retry-After',Math.ceil((windowMs-(now-old.window))/1000));res.status(429).json({error:'Too many requests. Please try again shortly.'});return false}return true}
function canMutate(req:Request,session:{csrf:string}){const supplied=req.get('x-dashboard-csrf')||'';if(!supplied||supplied.length!==session.csrf.length)return false;return crypto.timingSafeEqual(Buffer.from(session.csrf),Buffer.from(supplied))}
async function canManageGuild(client:Client,guildId:string,userId:string){const guild=client.guilds.cache.get(guildId);if(!guild)return false;if(guild.ownerId===userId)return true;const member=await guild.members.fetch(userId).catch(()=>null);return Boolean(member&&(member.permissions.has(PermissionFlagsBits.Administrator)||member.permissions.has(PermissionFlagsBits.ManageGuild)))}
function requireAuth(req:Request,res:Response){const session=getSession(req);if(!session){res.status(401).json({error:'Authentication required.'});return null}return session}
function requireMutation(req:Request,res:Response,session:any){if(!canMutate(req,session)){res.status(403).json({error:'Invalid dashboard security token.'});return false}return true}
function clearOAuthState(res:Response){res.setHeader('Set-Cookie',`${OAUTH_STATE_COOKIE}=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0`)}
function setOAuthState(res:Response,state:string){res.setHeader('Set-Cookie',`${OAUTH_STATE_COOKIE}=${encodeURIComponent(state)}; HttpOnly; Secure; SameSite=Lax; Path=/auth; Max-Age=${OAUTH_STATE_TTL/1000}`)}
function redirectLoginFailure(res:Response,message:string){return res.redirect(`/dashboard/?auth_error=${encodeURIComponent(message)}`)}

export function createDashboardRouter(client:Client){
 const router=express.Router();
 router.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()');next()});
 router.get('/auth/login',(req,res)=>{if(!rateLimit(req,res,10,10*60_000))return;if(!process.env.DISCORD_CLIENT_ID||!process.env.DISCORD_CLIENT_SECRET||!secret)return res.status(503).send('Dashboard authentication is not configured.');const state=b64(crypto.randomBytes(32));setOAuthState(res,state);const params=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:redirectUri(req),scope:'identify guilds',state});res.redirect(`https://discord.com/oauth2/authorize?${params.toString()}`)});
 router.get('/auth/callback',async(req,res)=>{if(!rateLimit(req,res,20,10*60_000))return;try{const code=typeof req.query.code==='string'?req.query.code:'';const returnedState=typeof req.query.state==='string'?req.query.state:'';const expectedState=cookie(req,OAUTH_STATE_COOKIE)||'';clearOAuthState(res);if(req.query.error){return redirectLoginFailure(res,req.query.error==='access_denied'?'Discord login was cancelled.':'Discord login could not be completed. Please try again.')}if(!code||!returnedState||!expectedState||returnedState.length!==expectedState.length||!crypto.timingSafeEqual(Buffer.from(returnedState),Buffer.from(expectedState)))return redirectLoginFailure(res,'Login session expired or was interrupted. Please click Continue with Discord again.');const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID!,client_secret:process.env.DISCORD_CLIENT_SECRET!,grant_type:'authorization_code',code,redirect_uri:redirectUri(req)});const token=await discordJson('https://discord.com/api/v10/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!token.access_token)throw new Error('Discord returned no access token.');const user=await discordJson('https://discord.com/api/v10/users/@me',{headers:{Authorization:`Bearer ${token.access_token}`}});const csrf=b64(crypto.randomBytes(32));const sessionToken=seal({userId:user.id,username:user.username,accessToken:token.access_token,csrf,exp:Date.now()+SESSION_TTL});res.setHeader('Set-Cookie',`${SESSION_COOKIE}=${encodeURIComponent(sessionToken)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${SESSION_TTL/1000}`);res.redirect('/dashboard/')}catch(e){return redirectLoginFailure(res,e instanceof Error&&/Discord API (400|401|403)/.test(e.message)?'Discord rejected the login. Please start a fresh login.':'Discord login temporarily failed. Please try again.')}});
 router.post('/auth/logout',(_req,res)=>{res.setHeader('Set-Cookie',`${SESSION_COOKIE}=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0`);res.json({ok:true})});
 router.get('/api/me',async(req,res)=>{if(!rateLimit(req,res,60,60_000))return;const session=getSession(req);if(!session)return res.status(401).json({authenticated:false});try{const user=await discordJson('https://discord.com/api/v10/users/@me',{headers:{Authorization:`Bearer ${session.accessToken}`}});return res.json({authenticated:true,csrf:session.csrf,user:{id:user.id,username:user.username,global_name:user.global_name,avatar:user.avatar}})}catch{return res.status(401).json({authenticated:false})}});
 router.get('/api/guilds',async(req,res)=>{if(!rateLimit(req,res,60,60_000))return;const session=requireAuth(req,res);if(!session)return;try{const result:any[]=[];for(const guild of client.guilds.cache.values())if(await canManageGuild(client,guild.id,session.userId))result.push({id:guild.id,name:guild.name,icon:guild.icon,owner:guild.ownerId===session.userId});return res.json({guilds:result})}catch{return res.status(500).json({error:'Unable to load servers.'})}});
 router.get('/api/guild/:guildId/bootstrap',async(req,res)=>{if(!rateLimit(req,res,60,60_000))return;const session=requireAuth(req,res);if(!session)return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});const guild=client.guilds.cache.get(guildId)!;const settings=getGuildSettings(guildId);const cases=db.prepare('SELECT COUNT(*) count FROM infractions WHERE guild_id=?').get(guildId) as {count:number};const warnings=db.prepare("SELECT COUNT(*) count FROM infractions WHERE guild_id=? AND type='warn'").get(guildId) as {count:number};const audit=db.prepare('SELECT * FROM audit_events WHERE guild_id=? ORDER BY timestamp DESC LIMIT 20').all(guildId);const roles=guild.roles.cache.filter(r=>!r.managed).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,position:r.position}));const channels=guild.channels.cache.filter(c=>c.isTextBased()).map(c=>({id:c.id,name:c.name,type:c.type}));const statuses=db.prepare('SELECT id,text,type,position FROM statuses WHERE guild_id=? ORDER BY position,id').all(guildId);const commandPermissions=db.prepare('SELECT command_name,role_id FROM command_permissions WHERE guild_id=? ORDER BY command_name,role_id').all(guildId);return res.json({guild:{id:guild.id,name:guild.name,icon:guild.icon},bot:{online:client.ws.status===0,username:client.user?.tag||null,uptime:Math.floor(process.uptime()),latency:client.ws.ping},settings,stats:{members:guild.memberCount,cases:cases.count,warnings:warnings.count},audit,roles,channels,statuses,commandPermissions})});
 router.post('/api/guild/:guildId/config',express.json({limit:'32kb'}),async(req,res)=>{if(!rateLimit(req,res,30,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});const allowed=new Set(['prefix','mod_log_channel','staff_roles','automod_enabled','automod_profanity','automod_caps','automod_links','automod_spam_threshold','automod_mention_limit','automod_invites','automod_blocked_words','automod_punishment','raid_mode','raid_threshold','raid_window_seconds','status_rotation_enabled','status_rotation_interval','security_enabled','security_action','security_threshold','security_window_seconds','security_trusted_users']);const body=req.body||{};try{for(const[k,v]of Object.entries(body)){if(!allowed.has(k))continue;if(k==='prefix'&&(typeof v!=='string'||v.length<1||v.length>5))throw new Error('Prefix must be 1-5 characters.');if(k==='mod_log_channel'&&v!==null&&typeof v!=='string')throw new Error('Invalid channel.');if((k==='staff_roles'||k==='security_trusted_users')&&typeof v!=='string')throw new Error(`Invalid ${k}.`);if((k.includes('threshold')||k.includes('interval')||k.includes('limit')||k.includes('window_seconds'))&&(typeof v!=='number'||!Number.isFinite(v)))throw new Error(`Invalid ${k}.`);if(k==='security_action'&&(typeof v!=='string'||!['alert','lockdown','ban_and_lockdown'].includes(v)))throw new Error('Invalid security action.');if(k==='automod_punishment'&&(typeof v!=='string'||!['delete','warn','timeout'].includes(v)))throw new Error('Invalid AutoMod punishment.');setGuildSetting(guildId,k as any,v as any)}return res.json({ok:true,settings:getGuildSettings(guildId)})}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'Invalid configuration.'})}});
 router.post('/api/guild/:guildId/security-action',express.json({limit:'8kb'}),async(req,res)=>{if(!rateLimit(req,res,10,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});const guild=client.guilds.cache.get(guildId);if(!guild)return res.status(404).json({error:'Server not found.'});const action=req.body?.action;if(action!=='lockdown'&&action!=='unlock')return res.status(400).json({error:'Invalid security action.'});try{const member=await guild.members.fetch(session.userId);if(!member.permissions.has(PermissionFlagsBits.ManageChannels)&&!member.permissions.has(PermissionFlagsBits.Administrator))return res.status(403).json({error:'Manage Channels permission is required.'});const result=action==='lockdown'?await enableLockdown(guild,`Dashboard security ${action} by ${session.userId}`):await disableLockdown(guild,`Dashboard security ${action} by ${session.userId}`);if(!result.ok)return res.status(400).json({error:result.reason});return res.json({ok:true,result,settings:getGuildSettings(guildId)})}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'Security action failed.'})}});
 router.post('/api/guild/:guildId/command-permissions',express.json({limit:'16kb'}),async(req,res)=>{if(!rateLimit(req,res,20,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});if(session.userId!==process.env.OWNER_ID)return res.status(403).json({error:'Only the bot owner can change command role permissions.'});const {action,commandName,roleId}=req.body||{};const normalized=typeof commandName==='string'?commandName.trim().replace(/^[/!]/,'').toLowerCase():'';if(!/^[a-z0-9][a-z0-9_-]{0,31}$/i.test(normalized))return res.status(400).json({error:'Invalid command name.'});if(!['add','remove','reset'].includes(action))return res.status(400).json({error:'Invalid permission action.'});if(action!=='reset'&&(!/^[0-9]{15,25}$/.test(String(roleId))))return res.status(400).json({error:'Invalid role ID.'});const command=(client as any).commands?.get(normalized);if(!command||normalized==='command-permission')return res.status(400).json({error:'Unknown or protected command.'});const role=guildRole(client,guildId,String(roleId));if(action!=='reset'&&(!role||role.managed||role.id===guildId))return res.status(400).json({error:'Select an existing, non-managed server role.'});if(action==='add')db.prepare('INSERT OR IGNORE INTO command_permissions(guild_id,command_name,role_id) VALUES(?,?,?)').run(guildId,normalized,String(roleId));if(action==='remove')db.prepare('DELETE FROM command_permissions WHERE guild_id=? AND command_name=? AND role_id=?').run(guildId,normalized,String(roleId));if(action==='reset')db.prepare('DELETE FROM command_permissions WHERE guild_id=? AND command_name=?').run(guildId,normalized);return res.json({ok:true,commandPermissions:db.prepare('SELECT command_name,role_id FROM command_permissions WHERE guild_id=? ORDER BY command_name,role_id').all(guildId)})});
 router.post('/api/guild/:guildId/statuses',express.json({limit:'16kb'}),async(req,res)=>{if(!rateLimit(req,res,30,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});const{action,text,type='PLAYING'}=req.body||{};try{if(action==='clear')db.prepare('DELETE FROM statuses WHERE guild_id=?').run(guildId);else if(action==='add'){if(typeof text!=='string'||!text.trim()||text.length>128)throw new Error('Status text must be 1-128 characters.');if(!['PLAYING','WATCHING','LISTENING','STREAMING','COMPETING'].includes(type))throw new Error('Invalid activity type.');const p=(db.prepare('SELECT COALESCE(MAX(position),-1)+1 p FROM statuses WHERE guild_id=?').get(guildId) as any).p;db.prepare('INSERT INTO statuses(guild_id,text,type,position) VALUES(?,?,?,?)').run(guildId,text.trim(),type,p)}else if(action==='apply'){const row=db.prepare('SELECT text,type FROM statuses WHERE guild_id=? ORDER BY position,id LIMIT 1').get(guildId) as any;if(row)client.user?.setActivity(row.text,{type:({PLAYING:0,STREAMING:1,LISTENING:2,WATCHING:3,COMPETING:5}as any)[row.type]??0})}else throw new Error('Unknown status action.');return res.json({ok:true,statuses:db.prepare('SELECT id,text,type,position FROM statuses WHERE guild_id=? ORDER BY position,id').all(guildId)})}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'Status update failed.'})}});
 router.delete('/api/guild/:guildId/statuses/:id',async(req,res)=>{if(!rateLimit(req,res,30,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});db.prepare('DELETE FROM statuses WHERE guild_id=? AND id=?').run(guildId,req.params.id);return res.json({ok:true})});
 setInterval(()=>{const now=Date.now();for(const[k,v]of rate)if(now-v.window>10*60_000)rate.delete(k)},5*60_000).unref();
 return router;
}
function guildRole(client:Client,guildId:string,roleId:string){return client.guilds.cache.get(guildId)?.roles.cache.get(roleId)}
