import crypto from 'crypto';
import express, { type Request, type Response } from 'express';
import path from 'path';
import type { Client } from 'discord.js';
import { PermissionFlagsBits } from 'discord.js';
import db from './db';
import { getGuildSettings, setGuildSetting } from './db/settings';

const SESSION_COOKIE='dashboard_session';
const SESSION_TTL=24*60*60*1000;
const secret=process.env.SESSION_SECRET||process.env.DASHBOARD_SESSION_SECRET;
if(!secret)console.warn('[Dashboard] SESSION_SECRET is not set; dashboard login is disabled until it is configured.');
const key=secret?crypto.createHash('sha256').update(secret).digest():null;
const loginStates=new Map<string,number>();
const rate=new Map<string,{window:number;count:number}>();
function b64(buf:Buffer){return buf.toString('base64url')}
function unb64(v:string){return Buffer.from(v,'base64url')}
function seal(payload:object){if(!key)throw new Error('Dashboard session secret is not configured.');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.from(JSON.stringify(payload)),encrypted=Buffer.concat([cipher.update(body),cipher.final()]);return `${b64(iv)}.${b64(cipher.getAuthTag())}.${b64(encrypted)}`}
function open(token:string){if(!key)return null;try{const [iv,tag,encrypted]=token.split('.');if(!iv||!tag||!encrypted)return null;const decipher=crypto.createDecipheriv('aes-256-gcm',key,unb64(iv));decipher.setAuthTag(unb64(tag));return JSON.parse(Buffer.concat([decipher.update(unb64(encrypted)),decipher.final()]).toString()) as {userId:string;username:string;accessToken:string;csrf:string;exp:number}}catch{return null}}
function getSession(req:Request){const token=req.headers.cookie?.match(new RegExp(`${SESSION_COOKIE}=([^;]+)`))?.[1];if(!token)return null;const data=open(decodeURIComponent(token));if(!data||data.exp<Date.now())return null;return data}
function origin(req:Request){if(process.env.DASHBOARD_PUBLIC_URL)return process.env.DASHBOARD_PUBLIC_URL.replace(/\/$/,'');const proto=req.headers['x-forwarded-proto']?.toString().split(',')[0]||req.protocol;const host=req.headers['x-forwarded-host']?.toString().split(',')[0]||req.get('host');return `${proto}://${host}`}
function redirectUri(req:Request){return process.env.DISCORD_REDIRECT_URI||`${origin(req)}/auth/callback`}
async function discordJson(url:string,init?:RequestInit){const r=await fetch(url,init);if(!r.ok)throw new Error(`Discord API ${r.status}`);return r.json() as Promise<any>}
function clientIp(req:Request){return req.ip||req.socket.remoteAddress||'unknown'}
function rateLimit(req:Request,res:Response,limit:number,windowMs:number){const key=`${clientIp(req)}:${req.path}`;const now=Date.now();const old=rate.get(key);if(!old||now-old.window>=windowMs){rate.set(key,{window:now,count:1});return true}old.count++;if(old.count>limit){res.setHeader('Retry-After',Math.ceil((windowMs-(now-old.window))/1000));res.status(429).json({error:'Too many requests. Please try again shortly.'});return false}return true}
function canMutate(req:Request,session:{csrf:string}){const supplied=req.get('x-dashboard-csrf')||'';if(!supplied||supplied.length!==session.csrf.length)return false;return crypto.timingSafeEqual(Buffer.from(session.csrf),Buffer.from(supplied))}
async function canManageGuild(client:Client,guildId:string,userId:string){const guild=client.guilds.cache.get(guildId);if(!guild)return false;if(guild.ownerId===userId)return true;const member=await guild.members.fetch(userId).catch(()=>null);return Boolean(member&&(member.permissions.has(PermissionFlagsBits.Administrator)||member.permissions.has(PermissionFlagsBits.ManageGuild)))}
function requireAuth(req:Request,res:Response){const session=getSession(req);if(!session){res.status(401).json({error:'Authentication required.'});return null}return session}
function requireMutation(req:Request,res:Response,session:any){if(!canMutate(req,session)){res.status(403).json({error:'Invalid dashboard security token.'});return false}return true}

export function createDashboardRouter(client:Client){
 const router=express.Router();
 router.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()');next()});
 router.get('/auth/login',(req,res)=>{if(!rateLimit(req,res,10,10*60_000))return;if(!process.env.DISCORD_CLIENT_ID||!process.env.DISCORD_CLIENT_SECRET||!secret)return res.status(503).send('Dashboard authentication is not configured.');const state=b64(crypto.randomBytes(24));loginStates.set(state,Date.now()+10*60_000);const params=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:redirectUri(req),scope:'identify guilds'});res.redirect(`https://discord.com/oauth2/authorize?${params.toString()}&state=${state}`)});
 router.get('/auth/callback',async(req,res)=>{if(!rateLimit(req,res,20,10*60_000))return;try{const code=typeof req.query.code==='string'?req.query.code:'';const state=typeof req.query.state==='string'?req.query.state:'';const expiry=loginStates.get(state);loginStates.delete(state);if(!code||!expiry||expiry<Date.now())return res.status(400).send('Invalid or expired login request.');const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID!,client_secret:process.env.DISCORD_CLIENT_SECRET!,grant_type:'authorization_code',code,redirect_uri:redirectUri(req)});const token=await discordJson('https://discord.com/api/v10/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const user=await discordJson('https://discord.com/api/v10/users/@me',{headers:{Authorization:`Bearer ${token.access_token}`}});const csrf=b64(crypto.randomBytes(32));const sessionToken=seal({userId:user.id,username:user.username,accessToken:token.access_token,csrf,exp:Date.now()+SESSION_TTL});res.setHeader('Set-Cookie',`${SESSION_COOKIE}=${encodeURIComponent(sessionToken)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${SESSION_TTL/1000}`);res.redirect('/dashboard/')}catch{res.status(502).send('Discord login failed. Check OAuth settings.')}});
 router.post('/auth/logout',(_req,res)=>{res.setHeader('Set-Cookie',`${SESSION_COOKIE}=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0`);res.json({ok:true})});
 router.get('/api/me',async(req,res)=>{if(!rateLimit(req,res,60,60_000))return;const session=getSession(req);if(!session)return res.status(401).json({authenticated:false});try{const user=await discordJson('https://discord.com/api/v10/users/@me',{headers:{Authorization:`Bearer ${session.accessToken}`}});return res.json({authenticated:true,csrf:session.csrf,user:{id:user.id,username:user.username,global_name:user.global_name,avatar:user.avatar}})}catch{return res.status(401).json({authenticated:false})}});
 router.get('/api/guilds',async(req,res)=>{if(!rateLimit(req,res,60,60_000))return;const session=requireAuth(req,res);if(!session)return;try{const result:any[]=[];for(const guild of client.guilds.cache.values())if(await canManageGuild(client,guild.id,session.userId))result.push({id:guild.id,name:guild.name,icon:guild.icon,owner:guild.ownerId===session.userId});return res.json({guilds:result})}catch{return res.status(500).json({error:'Unable to load servers.'})}});
 router.get('/api/guild/:guildId/bootstrap',async(req,res)=>{if(!rateLimit(req,res,60,60_000))return;const session=requireAuth(req,res);if(!session)return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});const guild=client.guilds.cache.get(guildId)!;const settings=getGuildSettings(guildId);const cases=db.prepare('SELECT COUNT(*) count FROM infractions WHERE guild_id=?').get(guildId) as {count:number};const warnings=db.prepare("SELECT COUNT(*) count FROM infractions WHERE guild_id=? AND type='warn'").get(guildId) as {count:number};const audit=db.prepare('SELECT * FROM audit_events WHERE guild_id=? ORDER BY timestamp DESC LIMIT 20').all(guildId);const roles=guild.roles.cache.filter(r=>!r.managed).sort((a,b)=>b.position-a.position).map(r=>({id:r.id,name:r.name,position:r.position}));const channels=guild.channels.cache.filter(c=>c.isTextBased()).map(c=>({id:c.id,name:c.name,type:c.type}));const statuses=db.prepare('SELECT id,text,type,position FROM statuses WHERE guild_id=? ORDER BY position,id').all(guildId);return res.json({guild:{id:guild.id,name:guild.name,icon:guild.icon},bot:{online:client.ws.status===0,username:client.user?.tag||null,uptime:Math.floor(process.uptime()),latency:client.ws.ping},settings,stats:{members:guild.memberCount,cases:cases.count,warnings:warnings.count},audit,roles,channels,statuses})});
 router.post('/api/guild/:guildId/config',express.json({limit:'32kb'}),async(req,res)=>{if(!rateLimit(req,res,30,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});const allowed=new Set(['prefix','mod_log_channel','staff_roles','automod_enabled','automod_profanity','automod_caps','automod_links','automod_spam_threshold','automod_mention_limit','automod_invites','automod_blocked_words','automod_punishment','raid_mode','raid_threshold','raid_window_seconds','status_rotation_enabled','status_rotation_interval']);const body=req.body||{};try{for(const[k,v]of Object.entries(body)){if(!allowed.has(k))continue;if(k==='prefix'&&(typeof v!=='string'||v.length<1||v.length>5))throw new Error('Prefix must be 1-5 characters.');if(k==='mod_log_channel'&&v!==null&&typeof v!=='string')throw new Error('Invalid channel.');if(k==='staff_roles'&&typeof v!=='string')throw new Error('Invalid staff roles.');if(k.includes('threshold')||k.includes('interval')||k.includes('limit')){if(typeof v!=='number'||!Number.isFinite(v))throw new Error(`Invalid ${k}.`)}if(k==='automod_punishment'&&(typeof v!=='string'||!['delete','warn','timeout'].includes(v)))throw new Error('Invalid AutoMod punishment.');setGuildSetting(guildId,k as any,v as any)}return res.json({ok:true,settings:getGuildSettings(guildId)})}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'Invalid configuration.'})}});
 router.post('/api/guild/:guildId/statuses',express.json({limit:'16kb'}),async(req,res)=>{if(!rateLimit(req,res,30,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});const{action,text,type='PLAYING'}=req.body||{};try{if(action==='clear')db.prepare('DELETE FROM statuses WHERE guild_id=?').run(guildId);else if(action==='add'){if(typeof text!=='string'||!text.trim()||text.length>128)throw new Error('Status text must be 1-128 characters.');if(!['PLAYING','WATCHING','LISTENING','STREAMING','COMPETING'].includes(type))throw new Error('Invalid activity type.');const p=(db.prepare('SELECT COALESCE(MAX(position),-1)+1 p FROM statuses WHERE guild_id=?').get(guildId) as any).p;db.prepare('INSERT INTO statuses(guild_id,text,type,position) VALUES(?,?,?,?)').run(guildId,text.trim(),type,p)}else if(action==='apply'){const row=db.prepare('SELECT text,type FROM statuses WHERE guild_id=? ORDER BY position,id LIMIT 1').get(guildId) as any;if(row)client.user?.setActivity(row.text,{type:({PLAYING:0,STREAMING:1,LISTENING:2,WATCHING:3,COMPETING:5}as any)[row.type]??0})}else throw new Error('Unknown status action.');return res.json({ok:true,statuses:db.prepare('SELECT id,text,type,position FROM statuses WHERE guild_id=? ORDER BY position,id').all(guildId)})}catch(e){return res.status(400).json({error:e instanceof Error?e.message:'Status update failed.'})}});
 router.delete('/api/guild/:guildId/statuses/:id',async(req,res)=>{if(!rateLimit(req,res,30,60_000))return;const session=requireAuth(req,res);if(!session||!requireMutation(req,res,session))return;const guildId=req.params.guildId;if(!await canManageGuild(client,guildId,session.userId))return res.status(403).json({error:'You cannot manage this server.'});db.prepare('DELETE FROM statuses WHERE guild_id=? AND id=?').run(guildId,req.params.id);return res.json({ok:true})});
 setInterval(()=>{const now=Date.now();for(const[k,v]of loginStates)if(v<now)loginStates.delete(k);for(const[k,v]of rate)if(now-v.window>10*60_000)rate.delete(k)},5*60_000).unref();
 return router;
}
export function dashboardStaticPath(){return path.join(process.cwd(),'dashboard')}
